/**
 * HerType 词库引擎
 * ----------------------------------------------------------------
 * 6 大分类（按「攻击机制」而非「字面」划分）：
 *   maternal   母职/亲属羞辱   —— 用侵犯对方母亲完成攻击，预设女性是男性所有物
 *   sexual     性经验羞辱       —— 用女性性活跃度=低价值，规训女性身体
 *   feminine   女性气质贬低     —— 把「像女人」当成侮辱，本质贬低女性
 *   rivalry    女性竞争污名     —— 给女性的能动性/野心贴负面标签
 *   appearance 外貌规训         —— 用外貌评判女性价值，男性不受此约束
 *   merit      能力性化否定     —— 把女性成就归因于性交易而非能力（最隐蔽、杀伤最大）
 *
 * 每条词条字段：
 *   trigger    触发词（命中的原词）
 *   category   所属分类（见上）
 *   severity   严重度 1-5
 *   mirror     镜像模式下的「性别对调」结果（让人看见双标的荒谬）
 *   neutral    中性模式下的占位替换
 *   explain    学习模式下摊开的「机制解释」——这是产品最锋利的部分
 */

const CATEGORIES = {
  maternal:   { label: "母职 / 亲属羞辱", color: "#d6336c" },
  sexual:     { label: "性经验羞辱",       color: "#c2255c" },
  feminine:   { label: "女性气质贬低",     color: "#9c36b5" },
  rivalry:    { label: "女性竞争污名",     color: "#e8590c" },
  appearance: { label: "外貌规训",         color: "#e67700" },
  merit:      { label: "能力性化否定",     color: "#a61e4d" },
};

const LEXICON = [
  // ① 母职 / 亲属羞辱 ---------------------------------------------------
  {
    trigger: "他妈的",
    category: "maternal",
    severity: 2,
    mirror: "他爸的",
    neutral: "［脏话］",
    explain: "把「妈」当成万能脏话载体，预设侮辱一个人的母亲就能羞辱他——这背后是「女性（母亲）是男性附属品」的所有权逻辑。换成「他爸的」你会觉得别扭，正说明这套羞辱只朝一个性别开火。",
    rewrite: "可恶",
  },
  {
    trigger: "她妈的",
    category: "maternal",
    severity: 2,
    mirror: "她爸的",
    neutral: "［脏话］",
    explain: "和「他妈的」同源的口头禅，攻击通道仍是「妈」。无论主语是他还是她，被拿来当脏话垫背的永远是母亲——这就是父权语言的默认设置。",
    rewrite: "可恶",
  },
  {
    trigger: "你妈",
    category: "maternal",
    severity: 4,
    mirror: "你爸",
    neutral: "［亲属攻击］",
    explain: "通过攻击对方母亲来攻击对方本人，母亲在这里不是「人」，而是男性荣誉的容器。一旦母亲「被侵犯」，受辱的被默认是儿子——女性的主体性被彻底抹去。",
    rewrite: "（去掉这句攻击）",
  },
  {
    trigger: "妈卖批",
    category: "maternal",
    severity: 5,
    mirror: "爸卖批",
    neutral: "［性化亲属攻击］",
    explain: "同时叠加「母职」和「性交易」两层羞辱：用「母亲卖身」作为终极侮辱，既物化母亲、又把女性性行为等同于堕落。",
    rewrite: "（去掉这句攻击）",
  },
  {
    trigger: "草泥马",
    category: "maternal",
    severity: 2,
    mirror: "草泥爸",
    neutral: "［脏话］",
    explain: "「操你妈」的谐音变体。换皮不换骨——攻击逻辑仍是把对方母亲性化、当作攻击通道。谐音让它显得无害，但机制完全一样。",
    rewrite: "真是气死我了",
  },
  {
    trigger: "nmsl",
    category: "maternal",
    severity: 4,
    mirror: "你爸死了",
    neutral: "［亲属攻击缩写］",
    explain: "「你妈死了」的拼音缩写，网络高频攻击语。缩写让它显得是玩笑，但诅咒的核心仍是对方母亲的死亡——把女性亲属当成攻击的靶心。",
    rewrite: "（去掉这句诅咒）",
  },
  {
    trigger: "tmd",
    category: "maternal",
    severity: 2,
    mirror: "他爸的",
    neutral: "［脏话缩写］",
    explain: "「他妈的」的拼音缩写。缩写淡化了字面，但「妈」依旧是被借用的羞辱通道——口头禅级别的父权惯性。",
    rewrite: "真烦",
  },
  {
    trigger: "你妈死了",
    category: "maternal",
    severity: 5,
    mirror: "你爸死了",
    neutral: "［亲属诅咒］",
    explain: "直接诅咒对方母亲死亡，用女性亲属的生命当攻击筹码。母亲在此再次沦为羞辱男性的工具，而非独立的人。",
    rewrite: "（去掉这句诅咒）",
  },

  // ② 性经验羞辱 -------------------------------------------------------
  {
    trigger: "婊子",
    category: "sexual",
    severity: 5,
    mirror: "",
    neutral: "［性羞辱词］",
    explain: "通过暗示女性性经验丰富来完成价值贬损。注意：男性几乎没有对应的贬义词——性活跃的男性被夸「能力强」，女性却被骂「婊」。这就是荡妇羞辱的双重标准。",
    rewrite: "这个人",
  },
  {
    trigger: "骚货",
    category: "sexual",
    severity: 5,
    mirror: "",
    neutral: "［性羞辱词］",
    explain: "把女性表达欲望、展示身体污名化为「骚」。它规训的不是行为，而是「女性不该有性主体性」——女性的性只能是被动的、供他人评判的。",
    rewrite: "这个人",
  },
  {
    trigger: "公交车",
    category: "sexual",
    severity: 4,
    mirror: "",
    neutral: "［性羞辱比喻］",
    explain: "用「人人可上的公交车」比喻女性，把女性身体物化成公共交通工具。这种比喻彻底剥夺女性作为人的主体性，把她降格为可使用的物。",
    rewrite: "（去掉这个污名）",
  },
  {
    trigger: "破鞋",
    category: "sexual",
    severity: 4,
    mirror: "",
    neutral: "［性羞辱词］",
    explain: "用「穿旧的鞋」隐喻有过性经验的女性，预设女性像物品一样会「贬值」「变旧」。男性的性经验从不被这样计价。",
    rewrite: "（去掉这个污名）",
  },
  {
    trigger: "母狗",
    category: "sexual",
    severity: 5,
    mirror: "",
    neutral: "［性羞辱词］",
    explain: "把女性贬为发情的雌性牲畜，同时性化与去人化。「母」字精准锁定生理性别，是对女性身体和尊严的双重剥夺。",
    rewrite: "这个人",
  },
  {
    trigger: "荡妇",
    category: "sexual",
    severity: 5,
    mirror: "",
    neutral: "［性羞辱词］",
    explain: "荡妇羞辱的原型词。同样的性自由，男性是「风流倜傥」，女性就是「荡妇」——这套词专门惩罚拥有性自主权的女性。",
    rewrite: "这个人",
  },
  {
    trigger: "鸡",
    category: "sexual",
    severity: 4,
    mirror: "",
    neutral: "［性羞辱词］",
    explain: "用「鸡」指代性工作者并扩大化羞辱所有女性。值得注意的是：购买性服务的男性几乎不被污名，被羞辱、被治罪、被歧视的总是女性一方。",
    rewrite: "性工作者",
  },
  {
    trigger: "小三",
    category: "sexual",
    severity: 3,
    mirror: "",
    neutral: "［性道德审判词］",
    explain: "婚姻关系破裂时，舆论火力常集中在「小三」这个女性身上，而出轨的男方却被轻轻放过。它把道德责任性别化地压在女性头上。",
    rewrite: "婚姻里的第三方",
  },

  // ③ 女性气质贬低 -----------------------------------------------------
  {
    trigger: "娘炮",
    category: "feminine",
    severity: 4,
    mirror: "",
    neutral: "［气质羞辱词］",
    explain: "表面骂的是男性，实则贬低的是女性——它的杀伤力建立在「像女人是丢人的」这一预设上。骂一个男人「娘」，等于宣布女性气质天然低人一等。",
    rewrite: "这个人",
  },
  {
    trigger: "娘们唧唧",
    category: "feminine",
    severity: 3,
    mirror: "",
    neutral: "［气质羞辱词］",
    explain: "把「犹豫、情绪化、啰嗦」打包成「娘们」的特征并加以贬低。这既刻板化了女性，又把负面品质和女性绑定，强化「男性气质=优越」。",
    rewrite: "太磨叽",
  },
  {
    trigger: "娘娘腔",
    category: "feminine",
    severity: 3,
    mirror: "",
    neutral: "［气质羞辱词］",
    explain: "用「像女性的腔调」羞辱男性，预设温柔、细腻是丢人的。它惩罚不符合刚硬男性气质的人，根子上仍是「女性特质低人一等」。",
    rewrite: "这个人",
  },
  {
    trigger: "妇人之仁",
    category: "feminine",
    severity: 2,
    mirror: "",
    neutral: "［气质贬低词］",
    explain: "把「心软、共情、不忍」贬为女性专属的缺点。共情明明是中性品质，却被冠以「妇人」并视为成事的障碍——这是把人性优点性别化、再贬低。",
    rewrite: "太心软",
  },
  {
    trigger: "头发长见识短",
    category: "feminine",
    severity: 4,
    mirror: "",
    neutral: "［气质贬低俗语］",
    explain: "用外在的「长发」直接推断女性「见识短」，把智识缺陷和女性身体特征强行绑定。男性犯蠢从不会被归因于「你是男的」。",
    rewrite: "见识不够",
  },
  {
    trigger: "妇道人家",
    category: "feminine",
    severity: 2,
    mirror: "",
    neutral: "［性别规训词］",
    explain: "用「妇道」框定女性应有的本分和边界，预设女性的言行需符合一套专为她们设的规矩。男性没有对应的「夫道人家」来限制。",
    rewrite: "女性",
  },
  {
    trigger: "像个娘们",
    category: "feminine",
    severity: 3,
    mirror: "",
    neutral: "［气质羞辱词］",
    explain: "把「娘们」当成负面参照系来贬低他人，无论对象是男是女，都建立在「女性=低等」的预设上。",
    rewrite: "太婆婆妈妈",
  },

  // ④ 女性竞争污名 -----------------------------------------------------
  {
    trigger: "绿茶婊",
    category: "rivalry",
    severity: 4,
    mirror: "绿茶男",
    neutral: "［竞争污名词］",
    explain: "专门污名化「会经营人际关系、懂得展示自己」的女性。男性做同样的事叫「情商高」「会来事」，女性做就成了「心机」「绿茶」——惩罚的是女性的社交能动性。",
    rewrite: "这个人",
  },
  {
    trigger: "心机婊",
    category: "rivalry",
    severity: 4,
    mirror: "心机男",
    neutral: "［竞争污名词］",
    explain: "把女性的策略性、目标感污名化为「心机」。同样的深思熟虑，男性叫「有城府、深谋远虑」，女性却被骂「婊」——女性的野心本身被当成原罪。",
    rewrite: "心思深的人",
  },
  {
    trigger: "捞女",
    category: "rivalry",
    severity: 4,
    mirror: "捞男",
    neutral: "［竞争污名词］",
    explain: "污名化在婚恋中考量经济条件的女性。男性「找门当户对」叫务实，女性同样做就被骂「捞」——惩罚的是女性在两性市场中争取自身利益的行为。",
    rewrite: "现实的人",
  },
  {
    trigger: "白莲花",
    category: "rivalry",
    severity: 3,
    mirror: "",
    neutral: "［竞争污名词］",
    explain: "讽刺「装清纯、装无辜」的女性。它制造一个双输陷阱：女性强势叫「心机」，柔和又叫「白莲花」——无论怎么表现都有原罪。",
    rewrite: "这个人",
  },
  {
    trigger: "傍大款",
    category: "rivalry",
    severity: 3,
    mirror: "傍富婆",
    neutral: "［竞争污名词］",
    explain: "污名化经济条件较好婚恋关系中的女性。男性「娶了富家千金」常被恭喜「会找」，女性却被贬为「傍」——能动性被解读成投机。",
    rewrite: "看重经济条件",
  },
  {
    trigger: "拜金女",
    category: "rivalry",
    severity: 3,
    mirror: "拜金男",
    neutral: "［竞争污名词］",
    explain: "把女性对经济保障的合理考量贬为「拜金」。男性追求财富叫「有事业心、上进」，女性同样的诉求却被道德化批判。",
    rewrite: "看重物质的人",
  },
  {
    trigger: "雌竞",
    category: "rivalry",
    severity: 2,
    mirror: "雄竞",
    neutral: "［竞争污名词］",
    explain: "用「雌竞」嘲讽女性之间的竞争，暗示女性争斗是出于嫉妒、肤浅。男性竞争被视为天经地义的奋斗，女性竞争却被特意性别化、矮化。",
    rewrite: "竞争",
  },

  // ⑤ 外貌规训 ---------------------------------------------------------
  {
    trigger: "恐龙",
    category: "appearance",
    severity: 3,
    mirror: "",
    neutral: "［外貌羞辱词］",
    explain: "用「恐龙」嘲讽女性长相，预设女性的核心价值是外貌、且必须供他人审视。男性极少因长相被群嘲——女性却被默认要为「好看」负责。",
    rewrite: "（去掉外貌评价）",
  },
  {
    trigger: "母猪",
    category: "appearance",
    severity: 4,
    mirror: "公猪",
    neutral: "［外貌羞辱词］",
    explain: "用雌性牲畜羞辱女性身材，双重物化：既贬低外貌，又用「母」字把攻击精准对准女性生理性别。男性发胖很少被这样动物化。",
    rewrite: "（去掉外貌攻击）",
  },
  {
    trigger: "人老珠黄",
    category: "appearance",
    severity: 3,
    mirror: "",
    neutral: "［年龄外貌规训］",
    explain: "把女性价值和年轻外貌绑定，预设女性「会过期」。男性变老叫「成熟、有魅力、大叔」，女性变老却是「珠黄」——同一件自然的事，只对女性计价。",
    rewrite: "上了年纪",
  },
  {
    trigger: "黄脸婆",
    category: "appearance",
    severity: 4,
    mirror: "",
    neutral: "［年龄外貌规训］",
    explain: "专门羞辱操持家务、为家庭付出而衰老的已婚女性。她的付出不被看见，反被嫌弃「不再年轻好看」——外貌被当成女性唯一被计价的资产。",
    rewrite: "操持家务的妻子",
  },
  {
    trigger: "波霸",
    category: "appearance",
    severity: 2,
    mirror: "",
    neutral: "［身体物化词］",
    explain: "用身体局部特征命名整个女性，把人简化为可供观看、评判的身体部件。男性极少被这样以某个身体部位代称。",
    rewrite: "（去掉身体评价）",
  },
  {
    trigger: "丑女",
    category: "appearance",
    severity: 3,
    mirror: "丑男",
    neutral: "［外貌羞辱词］",
    explain: "把「丑」当成对女性的核心否定，预设女性必须好看才有价值。男性的价值很少被「丑」一字全盘抹杀。",
    rewrite: "（去掉外貌评价）",
  },

  // ⑥ 能力性化否定（最隐蔽、最常被当玩笑）-------------------------------
  {
    trigger: "陪睡上位",
    category: "merit",
    severity: 5,
    mirror: "",
    neutral: "［能力性化否定］",
    explain: "把女性的职业成就归因于「性交易」而非能力。这是最隐蔽也最有杀伤力的羞辱——它系统性地否认女性可以靠实力成功，无论她多努力，成就都会被「她是不是睡上去的」消解。",
    rewrite: "靠不正当手段上位",
  },
  {
    trigger: "潜规则",
    category: "merit",
    severity: 4,
    mirror: "",
    neutral: "［能力性化否定］",
    explain: "当女性获得机会，「潜规则」成了默认怀疑。它把女性的能动性和成绩都性化，预设「女性只能用身体换资源」。男性的晋升极少被这样审视。",
    rewrite: "（去掉这个揣测）",
  },
  {
    trigger: "花瓶",
    category: "merit",
    severity: 3,
    mirror: "",
    neutral: "［能力性化否定］",
    explain: "把外貌好的女性贬为「只有外表、没有实力」。它制造一个陷阱：女性好看就是「花瓶」，不好看又被外貌羞辱——无论如何，能力都不被看见。",
    rewrite: "（去掉这个贬低）",
  },
  {
    trigger: "靠脸",
    category: "merit",
    severity: 3,
    mirror: "",
    neutral: "［能力性化否定］",
    explain: "当女性取得成绩，「还不是靠脸」成了惯性消解。它默认女性的成功必有外貌或性的成分，从根上拒绝承认女性的专业能力。",
    rewrite: "（去掉这个揣测）",
  },
  {
    trigger: "睡上去的",
    category: "merit",
    severity: 5,
    mirror: "",
    neutral: "［能力性化否定］",
    explain: "「陪睡上位」的口语变体。一句玩笑就能抹掉女性所有努力，把成就归因于性交易。它的伤害在于：说的人不必举证，被说的人却永远自证不清。",
    rewrite: "（去掉这个揣测）",
  },
  {
    trigger: "女司机",
    category: "merit",
    severity: 3,
    mirror: "男司机",
    neutral: "［能力性化否定］",
    explain: "出事故时特意强调「女司机」，把个体失误归因于性别群体。男性肇事远多于女性，却从没有「男司机」作为一个贬义标签存在。",
    rewrite: "司机",
  },
];

// 导出给 app.js 使用（浏览器全局）
window.HERTYPE = { CATEGORIES, LEXICON };
